config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  get 'home', to: 'pages#home', as: 'home'
  get 'about', to: 'pages#about', as: 'about'
  get 'sdflming', to: 'pages#sdflming', as: 'sdflming'

  get 'multiple_choice_questions/:id/ask', to: 'multiple_choice_questions#ask', as: 'ask_multiple_choice_question'
  post 'multiple_choice_questions/:id/ask', to: 'multiple_choice_questions#check_answer'
  post 'multiple_choice_questions', to: 'multiple_choice_questions#create', as: 'multiple_choice_questions'
  get 'multiple_choice_questions/:id/edit', to: 'multiple_choice_questions#edit', as: 'edit_multiple_choice_question'
  patch 'multiple_choice_questions/:id', to: 'multiple_choice_questions#update', as: 'multiple_choice_question'
  put 'multiple_choice_questions/:id', to: 'multiple_choice_questions#update'
  delete 'multiple_choice_questions/:id', to: 'multiple_choice_questions#destroy'

  get 'quizzes/:id/home', to: 'quizzes#home', as: 'quiz_home'
  get 'quizzes', to: 'quizzes#index', as: 'quizzes'
  post 'quizzes', to: 'quizzes#create'
  get 'quizzes/new', to: 'quizzes#new', as: 'new_quiz'
  get 'quizzes/:quiz_id/multiple_choice_questions/new', to: 'multiple_choice_questions#new', as: 'new_multiple_choice_question'
  get 'quizzes/:id/edit', to: 'quizzes#edit', as: 'edit_quiz'
  get 'quizzes/:id', to: 'quizzes#show', as: 'quiz'
  put 'quizzes/:id', to: 'quizzes#update'
  patch 'quizzes/:id', to: 'quizzes#update'
  delete 'quizzes/:id', to: 'quizzes#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    begin
      @quiz = Quiz.find(params[:id])
    rescue
      redirect_to home_url, alert: 'Error: Quiz not found'
    end
    @question = @quiz.questions.find(@quiz.question_ids.sample)
    # render 'quizzes/home.html.erb'
  end

  def index
    @quizzes = current_user.quizzes
    # render 'quizzes/index.html.erb'
  end

  def show
    begin
      @quiz = Quiz.find(params[:id])
    rescue
      redirect_to quizzes_url, alert: 'Error: Quiz not found'
    end
    # render 'quizzes/show.html.erb'
  end

  def new
    @quiz = Quiz.new
    # render 'quizzes/new.html.erb'
  end

  def create
    @quiz = Quiz.new(params.require(:quiz).permit(:title, :description))
    current_user.quizzes << @quiz
    if current_user.save
      redirect_to quiz_url(@quiz), notice: 'Quiz was successfully created.'
    else
      flash.now[:alert] = 'Error! Unable to create quiz.'
      render :new
    end
  end

  def edit
    begin
      @quiz = Quiz.find(params[:id])
    rescue
      redirect_to quizzes_url, alert: 'Error: Quiz not found'
    end
    # render 'quizzes/edit.html.erb'
  end

  def update
    begin
      @quiz = Quiz.find(params[:id])
    rescue
      redirect_to quizzes_url, alert: 'Error: Quiz not found'
    end
    if @quiz.update(params.require(:quiz).permit(:title, :description))
      redirect_to quiz_url(@quiz), notice: 'Quiz was successfully updated.'
    else
      flash.now[:alert] = 'Error! Unable to update quiz.'
      render :edit
    end
  end

  def destroy
    begin
      @quiz = Quiz.find(params[:id])
    rescue
      redirect_to quizzes_url, alert: 'Error: Quiz not found'
    end
    @quiz.destroy
    redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.'
  end

end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_with model: quiz, local: true do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
    <% if quiz.errors.full_messages_for(:title).any? %>
      <div class="invalid-feedback">
        <% quiz.errors.full_messages_for(:title).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
    <% if quiz.errors.full_messages_for(:description).any? %>
      <div class="invalid-feedback">
        <% quiz.errors.full_messages_for(:description).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<% provide(:title, 'Edit Quiz') %>

<main role="main" class="container">

  <h1>Edit Quiz</h1>

  <h2>Quiz Meta-Data</h2>

  <%= render 'form', quiz: @quiz %>
  
  <h2 style="margin-top: 1.5rem">Quiz Questions</h2>

  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">Question</th>
        <th scope="col">Answer</th>
        <th scope="col">Distractor 1</th>
        <th scope="col">Distractor 2</th>
        <th scope="col">Distractor 3</th>
        <th scope="col">Distractor 4</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @quiz.questions.each do |question| %>
        <tr>
          <td><%= question.question %></td>
          <td><%= question.answer %></td>
          <td><%= question.distractor_1 %></td>
          <td><%= question.distractor_2 %></td>
          <td><%= question.distractor_3 %></td>
          <td><%= question.distractor_4 %></td>
          <td>
            <%= link_to 'Edit', edit_multiple_choice_question_path(question) %>
            <%= link_to 'Destroy', multiple_choice_question_path(question), method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>
    <%= link_to 'New Multiple Choice Question', new_multiple_choice_question_path(@quiz) %>
  </p>

  <p>
    <%= link_to 'Back', quizzes_path %>
  </p>

</main><!-- /.container -->

app/views/quizzes/home.html.erb
<% provide(:title, 'Quiz') %>

<main role="main" class="container">

  <h1>Quiz: <%= @quiz.title %></h1>

  <p>
    <%= link_to 'Answer a randomly selected question', ask_multiple_choice_question_path(@question) %>
  </p>

</main><!-- /.container -->

app/views/quizzes/index.html.erb
<% provide(:title, 'Quizzes') %>

<main role="main" class="container">

  <h1>Quizzes</h1>

  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @quizzes.each do |quiz| %>
        <tr>
          <td><%= quiz.title %></td>
          <td><%= quiz.description %></td>
          <td>
            <%= link_to 'Show', quiz_path(quiz) %>
            <%= link_to 'Edit', edit_quiz_path(quiz) %>
            <%= link_to 'Destroy', quiz_path(quiz), method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>
    <%= link_to 'New Quiz', new_quiz_path %>
  </p>

</main><!-- /.container -->

app/views/quizzes/new.html.erb
<% provide(:title, 'New Quiz') %>

<main role="main" class="container">

  <h1>New Quiz</h1>

  <%= render 'form', quiz: @quiz %>

  <p>
    <%= link_to 'Back', quizzes_path %>
  </p>

</main><!-- /.container -->

app/views/quizzes/show.html.erb
<% provide(:title, 'Show Quiz') %>

<main role="main" class="container">

  <p>
    <b>Title:</b> <%= @quiz.title %>
  </p>

  <p>
    <b>Description:</b> <%= @quiz.description %>
  </p>

  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">Question</th>
        <th scope="col">Answer</th>
        <th scope="col">Distractor 1</th>
        <th scope="col">Distractor 2</th>
        <th scope="col">Distractor 3</th>
        <th scope="col">Distractor 4</th>
      </tr>
    </thead>
    <tbody>
      <% @quiz.questions.each do |question| %>
        <tr>
          <td><%= question.question %></td>
          <td><%= question.answer %></td>
          <td><%= question.distractor_1 %></td>
          <td><%= question.distractor_2 %></td>
          <td><%= question.distractor_3 %></td>
          <td><%= question.distractor_4 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>
    <%= link_to 'Edit', edit_quiz_path(@quiz) %> |
    <%= link_to 'Back', quizzes_path %>
  </p>

</main><!-- /.container -->