config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  get 'home', to: 'pages#home', as: 'home'
  get 'about', to: 'pages#about', as: 'about'
  get 'sdflming', to: 'pages#sdflming', as: 'sdflming'

  get 'multiple_choice_questions/:id/ask', to: 'multiple_choice_questions#ask', as: 'ask_multiple_choice_question'
  post 'multiple_choice_questions/:id/ask', to: 'multiple_choice_questions#check_answer'
  post 'multiple_choice_questions', to: 'multiple_choice_questions#create', as: 'multiple_choice_questions'
  get 'multiple_choice_questions/:id/edit', to: 'multiple_choice_questions#edit', as: 'edit_multiple_choice_question'
  patch 'multiple_choice_questions/:id', to: 'multiple_choice_questions#update', as: 'multiple_choice_question'
  put 'multiple_choice_questions/:id', to: 'multiple_choice_questions#update'
  delete 'multiple_choice_questions/:id', to: 'multiple_choice_questions#destroy'

  get 'quizzes/:id/home', to: 'quizzes#home', as: 'quiz_home'
  get 'quizzes', to: 'quizzes#index', as: 'quizzes'
  post 'quizzes', to: 'quizzes#create'
  get 'quizzes/new', to: 'quizzes#new', as: 'new_quiz'
  get 'quizzes/:quiz_id/multiple_choice_questions/new', to: 'multiple_choice_questions#new', as: 'new_multiple_choice_question'
  get 'quizzes/:id/edit', to: 'quizzes#edit', as: 'edit_quiz'
  get 'quizzes/:id', to: 'quizzes#show', as: 'quiz'
  put 'quizzes/:id', to: 'quizzes#update'
  patch 'quizzes/:id', to: 'quizzes#update'
  delete 'quizzes/:id', to: 'quizzes#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<% provide(:title, 'About') %>

<main role="main" class="container">

  <div class="starter-template">
    <h1>About</h1>

    <p>
      <%= link_to 'Scott Fleming', sdflming_path %>
    </p>
  </div>

</main><!-- /.container -->

app/views/pages/home.html.erb
<% provide(:title, 'Wapp') %>

<main role="main" class="container">

  <h1>Welcome to Wapp, the Quizzing App!</h1>

  <p>
    Choose a quiz to take:
  </p>

  <ul>
    <% @quizzes.each do |quiz| %>
      <li>
        <%= link_to quiz.title, quiz_home_path(quiz) %>:
        <%= quiz.description %>
      </li>
    <% end %>
  </ul>

</main><!-- /.container -->

app/views/pages/sdflming.html.erb
<% provide(:title, 'Scott Fleming') %>

<h1>Scott Fleming</h1>

<p>
Hello! Welcome to the page that's all about me!!
</p>

<p>
Here's my homepage: <%= link_to 'http://sdflem.github.io/', 'http://sdflem.github.io/' %>
</p>

<%= image_tag("scott-2018-square.jpg") %>

<p>
<%= link_to 'Home', home_path %>
</p>