config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  get 'home', to: 'pages#home', as: 'home'
  get 'about', to: 'pages#about', as: 'about'
  get 'sdflming', to: 'pages#sdflming', as: 'sdflming'

  get 'multiple_choice_questions/:id/ask', to: 'multiple_choice_questions#ask', as: 'ask_multiple_choice_question'
  post 'multiple_choice_questions/:id/ask', to: 'multiple_choice_questions#check_answer'
  post 'multiple_choice_questions', to: 'multiple_choice_questions#create', as: 'multiple_choice_questions'
  get 'multiple_choice_questions/:id/edit', to: 'multiple_choice_questions#edit', as: 'edit_multiple_choice_question'
  patch 'multiple_choice_questions/:id', to: 'multiple_choice_questions#update', as: 'multiple_choice_question'
  put 'multiple_choice_questions/:id', to: 'multiple_choice_questions#update'
  delete 'multiple_choice_questions/:id', to: 'multiple_choice_questions#destroy'

  get 'quizzes/:id/home', to: 'quizzes#home', as: 'quiz_home'
  get 'quizzes', to: 'quizzes#index', as: 'quizzes'
  post 'quizzes', to: 'quizzes#create'
  get 'quizzes/new', to: 'quizzes#new', as: 'new_quiz'
  get 'quizzes/:quiz_id/multiple_choice_questions/new', to: 'multiple_choice_questions#new', as: 'new_multiple_choice_question'
  get 'quizzes/:id/edit', to: 'quizzes#edit', as: 'edit_quiz'
  get 'quizzes/:id', to: 'quizzes#show', as: 'quiz'
  put 'quizzes/:id', to: 'quizzes#update'
  patch 'quizzes/:id', to: 'quizzes#update'
  delete 'quizzes/:id', to: 'quizzes#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/multiple_choice_question.rb
# == Schema Information
#
# Table name: multiple_choice_questions
#
#  id           :integer          not null, primary key
#  answer       :string
#  distractor_1 :string
#  distractor_2 :string
#  distractor_3 :string
#  distractor_4 :string
#  question     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  quiz_id      :integer
#
# Indexes
#
#  index_multiple_choice_questions_on_quiz_id  (quiz_id)
#

class MultipleChoiceQuestion < ApplicationRecord
  belongs_to :quiz,
    class_name: 'Quiz',
    foreign_key: 'quiz_id',
    inverse_of: :questions

  validates :question, presence: true
  validates :answer, presence: true
  validates :distractor_1, presence: true
end

app/controllers/multiple_choice_questions_controller.rb
class MultipleChoiceQuestionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:ask, :check_answer]

  def ask
    begin
      @multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
    rescue
      redirect_to home_url, alert: "Error: Question not found."
    end
    # render 'multiple_choice_questions/ask.html.erb'
  end

  def check_answer
    begin
      @multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
    rescue
      redirect_to home_url, alert: "Error: Question not found."
    end

    if params[:guess] && params[:guess] == '0'
      redirect_to quiz_home_url(@multiple_choice_question.quiz), notice: "Right! #{@multiple_choice_question.answer} was the correct answer."
    elsif params[:guess] && ['1', '2', '3', '4'].include?(params[:guess])
      redirect_to quiz_home_url(@multiple_choice_question.quiz), alert: "Wrong! #{@multiple_choice_question.answer} was the correct answer."
    else
      redirect_to quiz_home_url(@multiple_choice_question.quiz), alert: "Error: Invalid answer."
    end
  end

  # def show
  #   @multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
  #   # render 'multiple_choice_questions/show.html.erb'
  # end

  def new
    begin
      @quiz = Quiz.find(params[:quiz_id])
    rescue
      redirect_to quizzes_url, alert: 'Error: Quiz not found'
    end
    @multiple_choice_question = MultipleChoiceQuestion.new
    # render 'multiple_choice_questions/new.html.erb'
  end

  def create
    begin
      @quiz = Quiz.find(params[:quiz_id])
    rescue
      redirect_to quizzes_url, alert: 'Error: Quiz not found'
    end
    @multiple_choice_question = MultipleChoiceQuestion.new(params.require(:multiple_choice_question).permit(:question, :answer, :distractor_1, :distractor_2, :distractor_3, :distractor_4))
    @quiz.questions << @multiple_choice_question
    if @quiz.save
      redirect_to quiz_url(@quiz), notice: 'Multiple choice question was successfully created.'
    else
      flash.now[:alert] = 'Error! Unable to create multiple choice question.'
      render :new
    end
  end

  def edit
    @multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
    # render 'multiple_choice_questions/edit.html.erb'
  end

  def update
    begin
      @multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
    rescue
      redirect_to quizzes_url, alert: 'Error: Multiple choice question not found'
    end
    if @multiple_choice_question.update(params.require(:multiple_choice_question).permit(:question, :answer, :distractor_1, :distractor_2, :distractor_3, :distractor_4))
      redirect_to quiz_url(@multiple_choice_question.quiz), notice: 'Multiple choice question was successfully updated.'
    else
      flash.now[:alert] = 'Error! Unable to update multiple choice question.'
      render :edit
    end
  end

  def destroy
    begin
      @multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
    rescue
      redirect_to quizzes_url, alert: 'Error: Multiple choice question not found'
    end
    @quiz = @multiple_choice_question.quiz
    @multiple_choice_question.destroy
    redirect_to quiz_url(@quiz), notice: 'Multiple choice question was successfully destroyed.'
  end

end

app/helpers/multiple_choice_questions_helper.rb
module MultipleChoiceQuestionsHelper
end

app/views/multiple_choice_questions/_form.html.erb
<%= form_with model: multiple_choice_question, local: true do |form| %>
  <%= hidden_field_tag :quiz_id, quiz_id %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, class: 'form-control' %>
    <% if multiple_choice_question.errors.full_messages_for(:question).any? %>
      <div class="invalid-feedback">
        <% multiple_choice_question.errors.full_messages_for(:question).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer, class: 'form-control' %>
    <% if multiple_choice_question.errors.full_messages_for(:answer).any? %>
      <div class="invalid-feedback">
        <% multiple_choice_question.errors.full_messages_for(:answer).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :distractor_1 %>
    <%= form.text_field :distractor_1, class: 'form-control' %>
    <% if multiple_choice_question.errors.full_messages_for(:distractor_1).any? %>
      <div class="invalid-feedback">
        <% multiple_choice_question.errors.full_messages_for(:distractor_1).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :distractor_2 %>
    <%= form.text_field :distractor_2, class: 'form-control' %>
    <% if multiple_choice_question.errors.full_messages_for(:distractor_2).any? %>
      <div class="invalid-feedback">
        <% multiple_choice_question.errors.full_messages_for(:distractor_2).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :distractor_3 %>
    <%= form.text_field :distractor_3, class: 'form-control' %>
    <% if multiple_choice_question.errors.full_messages_for(:distractor_3).any? %>
      <div class="invalid-feedback">
        <% multiple_choice_question.errors.full_messages_for(:distractor_3).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :distractor_4 %>
    <%= form.text_field :distractor_4, class: 'form-control' %>
    <% if multiple_choice_question.errors.full_messages_for(:distractor_4).any? %>
      <div class="invalid-feedback">
        <% multiple_choice_question.errors.full_messages_for(:distractor_4).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/multiple_choice_questions/ask.html.erb
<% provide(:title, 'Answer This Question') %>

<main role="main" class="container">

  <h1>Answer This Question</h1>

  <p>
    <%= @multiple_choice_question.question %>
  </p>

  <%= form_tag do %>

    <%
      order = [0, 1, 2, 3, 4].shuffle
      order.each do |a|
    %>

      <% if a == 0 %>
        <p>
          <%= radio_button_tag(:guess, '0') %>
          <%= label_tag(:guess_0, @multiple_choice_question.answer) %>
        </p>

      <% elsif a == 1 %>
        <p>
          <%= radio_button_tag(:guess, '1') %>
          <%= label_tag(:guess_1, @multiple_choice_question.distractor_1) %>
        </p>

      <% elsif a == 2 && @multiple_choice_question.distractor_2 %>
        <p>
          <%= radio_button_tag(:guess, '2') %>
          <%= label_tag(:guess_2, @multiple_choice_question.distractor_2) %>
        </p>

      <% elsif a == 3 && @multiple_choice_question.distractor_3 %>
        <p>
          <%= radio_button_tag(:guess, '3') %>
          <%= label_tag(:guess_3, @multiple_choice_question.distractor_3) %>
        </p>

      <% elsif a == 4 && @multiple_choice_question.distractor_4 %>
        <p>
          <%= radio_button_tag(:guess, '4') %>
          <%= label_tag(:guess_4, @multiple_choice_question.distractor_4) %>
        </p>

      <% end %>

    <% end %>

    <%= submit_tag("Submit Answer") %>

  <% end %>

</main><!-- /.container -->

app/views/multiple_choice_questions/edit.html.erb
<% provide(:title, 'Edit Multiple Choice Question') %>

<main role="main" class="container">

  <h1>Edit Multiple Choice Question</h1>

  <%= render 'form', quiz_id: @multiple_choice_question.quiz.id, multiple_choice_question: @multiple_choice_question %>
  
  <p>
    <%= link_to 'Back', multiple_choice_questions_path %>
  </p>

</main><!-- /.container -->

app/views/multiple_choice_questions/index.html.erb
<% provide(:title, 'Multiple Choice Questions') %>

<main role="main" class="container">

  <h1>Multiple Choice Questions</h1>

  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">Question</th>
        <th scope="col">Answer</th>
        <th scope="col">Distractor 1</th>
        <th scope="col">Distractor 2</th>
        <th scope="col">Distractor 3</th>
        <th scope="col">Distractor 4</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @multiple_choice_questions.each do |question| %>
        <tr>
          <td><%= question.question %></td>
          <td><%= question.answer %></td>
          <td><%= question.distractor_1 %></td>
          <td><%= question.distractor_2 %></td>
          <td><%= question.distractor_3 %></td>
          <td><%= question.distractor_4 %></td>
          <td>
            <%= link_to 'Show', multiple_choice_question_path(question) %>
            <%= link_to 'Edit', edit_multiple_choice_question_path(question) %>
            <%= link_to 'Destroy', multiple_choice_question_path(question), method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>
    <%= link_to 'New Multiple Choice Question', new_multiple_choice_question_path %>
  </p>

</main><!-- /.container -->

app/views/multiple_choice_questions/new.html.erb
<% provide(:title, 'New Multiple Choice Question') %>

<main role="main" class="container">

  <h1>New Multiple Choice Question</h1>

  <%= render 'form', quiz_id: @quiz.id, multiple_choice_question: @multiple_choice_question %>

  <p>
    <%= link_to 'Back', multiple_choice_questions_path %>
  </p>

</main><!-- /.container -->

app/views/multiple_choice_questions/show.html.erb
<% provide(:title, 'Show Multiple Choice Question') %>

<main role="main" class="container">

  <p>
    <b>Question:</b> <%= @multiple_choice_question.question %>
  </p>

  <p>
    <b>Answer:</b> <%= @multiple_choice_question.answer %>
  </p>

  <p>
    <b>Distractor 1:</b> <%= @multiple_choice_question.distractor_1 %>
  </p>

  <p>
    <b>Distractor 2:</b> <%= @multiple_choice_question.distractor_2 %>
  </p>

  <p>
    <b>Distractor 3:</b> <%= @multiple_choice_question.distractor_3 %>
  </p>

  <p>
    <b>Distractor 4:</b> <%= @multiple_choice_question.distractor_4 %>
  </p>

  <p>
    <%= link_to 'Edit', edit_multiple_choice_question_path(@multiple_choice_question) %> |
    <%= link_to 'Back', multiple_choice_questions_path %>
  </p>

</main><!-- /.container -->