config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  get 'home', to: 'pages#home', as: 'home'
  get 'about', to: 'pages#about', as: 'about'
  get 'sdflming', to: 'pages#sdflming', as: 'sdflming'

  get 'multiple_choice_questions/:id/ask', to: 'multiple_choice_questions#ask', as: 'ask_multiple_choice_question'
  post 'multiple_choice_questions/:id/ask', to: 'multiple_choice_questions#check_answer'
  post 'multiple_choice_questions', to: 'multiple_choice_questions#create', as: 'multiple_choice_questions'
  get 'multiple_choice_questions/:id/edit', to: 'multiple_choice_questions#edit', as: 'edit_multiple_choice_question'
  patch 'multiple_choice_questions/:id', to: 'multiple_choice_questions#update', as: 'multiple_choice_question'
  put 'multiple_choice_questions/:id', to: 'multiple_choice_questions#update'
  delete 'multiple_choice_questions/:id', to: 'multiple_choice_questions#destroy'

  get 'quizzes/:id/home', to: 'quizzes#home', as: 'quiz_home'
  get 'quizzes', to: 'quizzes#index', as: 'quizzes'
  post 'quizzes', to: 'quizzes#create'
  get 'quizzes/new', to: 'quizzes#new', as: 'new_quiz'
  get 'quizzes/:quiz_id/multiple_choice_questions/new', to: 'multiple_choice_questions#new', as: 'new_multiple_choice_question'
  get 'quizzes/:id/edit', to: 'quizzes#edit', as: 'edit_quiz'
  get 'quizzes/:id', to: 'quizzes#show', as: 'quiz'
  put 'quizzes/:id', to: 'quizzes#update'
  patch 'quizzes/:id', to: 'quizzes#update'
  delete 'quizzes/:id', to: 'quizzes#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <%= link_to 'Wapp', home_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= active_class(home_path) %>">
            <%= link_to 'Home', home_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= active_class(about_path) %>">
            <%= link_to 'About', about_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= active_class(quizzes_path) %>">
            <%= link_to 'Teachers', quizzes_path, class: 'nav-link' %>
          </li>
<%
=begin
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
=end
%>
        </ul>

        <% if user_signed_in? %>
          <span class="navbar-text" style="margin-right: 1rem"><%= current_user.email %></span>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary' %>
        <% else %>
          <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-outline-primary' %>
        <% end %>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>